export const CREATE_CHARACTERS = "CREATE_CHARACTERS";
export const RETRIEVE_CHARACTERS = "RETRIEVE_CHARACTERS";
export const UPDATE_CHARACTERS = "UPDATE_CHARACTERS";
export const DELETE_CHARACTERS = "DELETE_CHARACTERS";
export const DELETE_ALL_CHARACTERS = "DELETE_ALL_CHARACTERS";
